### ISSUE TITLE
Sidekiq doesn't seem to restart after deploy

### ISSUE THREAD

**Issue by joshuajansen** [intercity/intercity-next#103]
I have to manually stop and scale after deploy to have Sidekiq use my latest code.

1. Stop running processes via /sidekiq webinterface
2. Deploy

Or if I forget to do step 1:

1. Deploy
2. Stop running processes via /sidekiq webinterface
3. SSH into server and run `dokku ps:scale formbox worker=1`

**Comment by jvanbaarsen** [comment]
@joshuajansen Do you have a `SCALE` or `DOKKU_SCALE` file present?

**Comment by jvanbaarsen** [comment]
Since at the time you did not have a DOKKU_SCALE file, and I added it, I "Assume" that it has been fixed.
