### ISSUE TITLE
New server modal is too small

### ISSUE THREAD

**Issue by michiels** [intercity/intercity-next#154]
When adding a new server, the modal's height is not high enough, making the form fields hard to navigate:

![schermafbeelding 2016-07-04 om 15 54 27](https://cloud.githubusercontent.com/assets/42268/16562939/bac8501c-41ff-11e6-8b56-cf620d521146.png)

**Comment by jvanbaarsen** [comment]
Relates to: https://github.com/jgthms/bulma/issues/208
