### ISSUE TITLE
Cut off / truncate environment variables

### ISSUE THREAD

**Issue by michiels** [intercity/intercity-next#155]
In the Environment Variables screen, things like long passwords or key bases aren't truncated (or hidden behind a "show" option) making the screen too wide to access the "delete" button. See attached screenshot:

![schermafbeelding 2016-07-05 om 11 23 50](https://cloud.githubusercontent.com/assets/42268/16580112/45ec41f0-42a3-11e6-8f2d-d6ba217893a7.png)

**Comment by michiels** [comment]
@jvanbaarsen is this a bug or an enhancement? :) or both?

**Comment by jvanbaarsen** [comment]
@michiels Thanks, I was sure there was already an issue for it. But apparently not :D 

In other news, you don't need to provide that variable. The buildpack will do that for you.

**Comment by michiels** [comment]
@jvanbaarsen You mean it generates the `SECRET_KEY_BASE`? Didn't know that! Thanks ;)

**Comment by jvanbaarsen** [comment]
@michiels Yes :-)
