### ISSUE TITLE
Adding the first environment variable keeps showing message "There are no environment variables"

### ISSUE THREAD

**Issue by michiels** [intercity/intercity-next#156]
When adding the first environment variable to an app, the "There are no environment variables" message isn't removed from the page. See screenshot:

![schermafbeelding 2016-07-05 om 11 23 50](https://cloud.githubusercontent.com/assets/42268/16580147/6a5fab8a-42a3-11e6-9175-54e546889782.png)

**Comment by jvanbaarsen** [comment]
Thanks, its a known bug, for which I believed there already was an issue, but seems to be not there. Thanks!
