### ISSUE TITLE
Intercity incorrectly gives update available notification

### ISSUE THREAD

**Issue by joshuajansen** [intercity/intercity-next#194]
My (up-to-date) Intercity instance says that my Dokku (v 0.7.1) is out of date, while this is actually the latest version atm:

![screen shot 2016-09-02 at 14 26 24](https://cloud.githubusercontent.com/assets/68570/18203773/5a2c73e8-7119-11e6-83b2-cb5773cf9b03.png)

**Comment by jvanbaarsen** [comment]
@joshuajansen Thanks for reporting. Will look into this!
