### ISSUE TITLE
Create/destroy deploy keys and install SSL certificate using sudo

### ISSUE THREAD

**Issue by joshuajansen** [intercity/intercity-next#226]
I've ran into an issue where deploy keys weren't added on a server that's set up with passwordless sudo.

This was because the intercity user can't write to dokku's `authorized_keys`. This can be resolved by executing this command with sudo: https://github.com/intercity/intercity-next/blob/e9225eb1ba5c0e0f412ca5a27da29143fc72d864/app/jobs/create_deploy_key_job.rb#L6

**Comment by joshuajansen** [comment]
It seems that adding SSL certificates has the same issue.

**Comment by michiels** [comment]
I think that this bug is solved for the deploy keys as we now add them via sudo. But it's still around for the custom SSL certificate. I'll rename this issue's title and add it to the current project focus.
