### ISSUE TITLE
Intercity not run after installation

### ISSUE THREAD

**Issue by w0www** [intercity/intercity-next#228]
When i enter in the URL i get this 

![imagen](https://cloud.githubusercontent.com/assets/1654762/26778954/c395fbda-49e3-11e7-921c-f08f821ff744.png)

**Comment by w0www** [comment]
Before install i need to do intercity-server update twice to work!

**Comment by jvanbaarsen** [comment]
@w0www Do you have Let's Encrypt enabled?

**Comment by w0www** [comment]
@jvanbaarsen yes. But when i update, work. But now have other problem after create a mysql installation. The error say template... [] nil or similar.

Thanks

**Comment by jvanbaarsen** [comment]
@w0www Ok thanks for the extra info. I ran into the "Update twice" issue also a couple of times. It's super hard to replicate :-( But I'll see if I can come up with a solution somewhere next week.
