### ISSUE TITLE
Fresh install using bootstrap.sh fails. Project still maintained?

### ISSUE THREAD

**Issue by genox** [intercity/intercity-next#268]
Hi,

Tried to install Intercity on a fresh install of dokku. The init process never finishes. While I'm able to access the web interface even if the script doesn't seem to be finished, it seems that assets like stylesheets and js can't be loaded.

Is this project still maintained? It seems that the "static assets can't be loaded" issue already exists and is 7 months old, so every new install since theoretically didn't work?

**Comment by axlroden** [comment]
yea the postgresql db needs a password variable, you can see it with docker-compose logs
Seems like a rather easy fix.

**Comment by genox** [comment]
Thanks for your reply. I've moved on to CapRover since.
