### ISSUE TITLE
Cant destroy a server PG::ForeignKeyViolation.

### ISSUE THREAD

**Issue by brambokdam** [intercity/intercity-next#29]
When destroying a server it gives a `PG::ForeignKeyViolation` exception if `active_services` or other related records are present.

**Comment by jvanbaarsen** [comment]
Ah, looks like we forgot a `dependend: :destroy`. Will you fix?

**Comment by brambokdam** [comment]
Yes already working on it!

**Comment by jvanbaarsen** [comment]
:+1:
