### ISSUE TITLE
Add a SECRET_KEY_BASE to apps by default

### ISSUE THREAD

**Issue by michiels** [intercity/intercity-next#71]
Every Rails app needs a `SECRET_KEY_BASE` ENV var by default to run. Can we add this as default ENV var when creating a new app from the UI?

**Comment by jvanbaarsen** [comment]
I'm very hesitate to add Rails defaults to IC. Since Dokku is platform independent. I want to try and keep IC that as well.

**Comment by michiels** [comment]
There are a few alternatives. Either providing "Add application" templates in the UI, or at least providing some documentation where this is described.

What I loved about IC classic was that I didn't have to think for a basic app setup. Just click, click and go. I'd love that same experience with Intercity Next too. Having to look it up in documentation is an extra barrier, but I guess it's a minimum when you you're not fond of providing sane defaults for most used hosting types for IC Next.

**Comment by jvanbaarsen** [comment]
I believe that for now having it in the documentation is the way to go. I created an issue for the documentation: https://github.com/intercity/intercity-next/issues/72

Closing this for now.

**Comment by michiels** [comment]
Allright. Let's try and keep the end user and his "job" in the back of our mind, not just the technology stack. I'd suggest we do add some hint to that documentation when creating an app in the UI!

**Comment by jvanbaarsen** [comment]
Sure, sounds good. I keep that in mind. I feel having a strong vision for the app is even more important, thats why I'm closing this :-) if you feel you can come up with a non-intrusive way to archieve this, go ahead. Can't guarantee a merge though.

**Comment by michiels** [comment]
Hah. I believe strong vision means making choices for your users, that's why I am very fond of providing a developer with the easiest and best way to do his job. Curious about your ideas on the smoothest way of having developers understand how to host rails apps in IC!

**Comment by jvanbaarsen** [comment]
@michiels I feel an important thing here is not introducing options that are not useful for people hosting Node apps for example.

I would be open to some sort of "dropdown" where you can select your tech stack, and that will set some defaults. But this should be optional.

**Comment by michiels** [comment]
Agreed! I was thinking about that exact dropdown.

**Comment by jvanbaarsen** [comment]
Ok! Can you create an issue with how you would like to implement this? For me this does not have massive priority, but good to already have the technical discussion.

**Comment by michiels** [comment]
Sure! I'll work on that! I don't think people would know how to host their Rails app on IC Next without having that feature or documentation. And: it saves some barriers in setting up a Rails app again. I've been setting up this Rails app for about 30 minutes now :)

**Comment by jvanbaarsen** [comment]
@michiels One thing that would be a big +1 for me, is that you can add your own custom "templates". So if people run a lot of Java apps, they can create their own Java template in a Yaml format:

```yaml
app_template:
  name: "java"
  env_vars:
    - KEY: "VALUE"
    - SECRET_KEY: secret (1)
  linked_services:
    - postgres
    - redis
```
(1) * Secret should be a "magic" value, which will generate a random key"

**Comment by michiels** [comment]
Yeah! Sounds good in providing some way to add custom templates. Let's focus on our own use cases first and see which other use cases might come in from other users :)

**Comment by jvanbaarsen** [comment]
@michiels Yeah ok, but I feel its important that all templates use the exact same underlying API. So even our own templates should use the "public" ways

**Comment by michiels** [comment]
Yep okay. How do you see managing these templates then? You can edit `YAML` files in the UI or something? Or do we read a git repository you can push to?

I suggest not making these feature too big up-front and let it first prove its use.

**Comment by jvanbaarsen** [comment]
@michiels It doesn't have to be in a public repo or whatever, we can still have "official" templates (which are our own templates). But they should be parsed by some sort of "AppTemplateParser".

**Comment by michiels** [comment]
Agreed
