### ISSUE TITLE
Backups get run before enabling them

### ISSUE THREAD

**Issue by michiels** [intercity/intercity-next#73]
In an app I just created, I see that there's already an automatic backup made (according to the backup tab), but I haven't enabled backups yet. Is it intended this way? Or is the backup scheduler started too early?

![schermafbeelding 2016-01-19 om 17 10 56](https://cloud.githubusercontent.com/assets/42268/12424282/bd4e8512-becf-11e5-98fc-5f3ef2a19a73.png)

**Comment by jvanbaarsen** [comment]
@michiels No this is not by design. I noticed it as well. Consider it a bug :-)

**Comment by michiels** [comment]
Cool thanks for quick clarification :)
