### ISSUE TITLE
When linking a service to an app, I want to get more feedback

### ISSUE THREAD

**Issue by jvanbaarsen** [intercity/intercity-next#8]
At this point we just redirect you back to the app show page. We should give more feedback when linking a service.

**Comment by jvanbaarsen** [comment]
This feature seems to be a bit more crucial then first thought. Since linking a service can easily take 20+ seconds.

**Comment by michiels** [comment]
@jvanbaarsen Right, perhaps some kind of "spinner" page or a little spinner in the add-on widget to indicate it's still installing/done after finishing.

**Comment by jvanbaarsen** [comment]
@michiels I want to make this the same as installing services on the server. So you get a label: "Linking" and it will be changed to "Linked" when ready.

**Comment by michiels** [comment]
@jvanbaarsen Allright! Btw, if you don't know Dokku/Docker, I think the concept of "linking" a service is not widely known. But we can see if our initial users understand that term. Otherwise, we can just call it "enable". So you "enable" a service for an app. Linking is a bit "under the hood".

**Comment by jvanbaarsen** [comment]
@michiels Yeah maybe something called "Attach". Since the service is already "Enabled" but not attached to your app yet. I'll see what looks/feels better; Enable or Attache. Good suggestion! 👍
