### ISSUE TITLE
Remove services and running containers when removing an app

### ISSUE THREAD

**Issue by michiels** [intercity/intercity-next#80]
I just removed an app, but I still see a Postgres service running for it. I suggest we remove corresponding services when removing an app.

**Comment by jvanbaarsen** [comment]
@michiels I assumed it did remove those links as well. But probably it does not actually kill the container, which might be a bug in Dokku. Will look further into this.

**Comment by michiels** [comment]
Agreed. I also see the app container still running. Maybe we can change this issue into: "clean everything up on app removal" or something?

**Comment by jvanbaarsen** [comment]
:+1:
