### ISSUE TITLE
Add a way to enable swap on a server

### ISSUE THREAD

**Issue by jvanbaarsen** [intercity/intercity-next#83]
For some servers we do want some swap space. Lets create a way you can opt-in to swap on your server.

**Comment by michiels** [comment]
Can you name some samples of why you want this so we can "measure" it towards the "SWAP will kill your SSD" argument: https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04?

**Comment by jvanbaarsen** [comment]
When you have a running app, and you upgrade the ruby version of that app. It needs to compile all the gems again, doing this on a server with a staging and production app will temporary increase the memory usage, and thus needing swap.

The reason I want it to opt-in/opt-out is that you can use it temporarily, for the exact reasons you linked to

**Comment by michiels** [comment]
Yeah ok, I get the problem (ran into it myself :D), but might it not be a better advice to just increase the RAM of the server? If you're deploying multiple times a day I think you should just get a bigger server?

**Comment by jvanbaarsen** [comment]
@michiels Its not on all deploys, just when you upgrade ruby version. that is not something you do everyday.

**Comment by michiels** [comment]
Okay. What would you set the option to by default?

**Comment by jvanbaarsen** [comment]
Off. I would suggest only adding swap if needed.

**Comment by michiels** [comment]
Cool! Let's make some kind of **danger** option out of this.

**Comment by jvanbaarsen** [comment]
:+1:

**Comment by michiels** [comment]
@jvanbaarsen Perhaps we can recognize if swap is already present on the server, and only then show the "Your server doesn't have swap yet. Do you want to enable it?" Since most hosting providers offer swap enabled by default. Currently, I'm only aware that DigitalOcean does not do this by default.

**Comment by jvanbaarsen** [comment]
@michiels Yeah that would be a great addition :-) That way we can show a "swap" widget, with the text: "Swap is currently not enabled [Enable swap]".
