### ISSUE TITLE
Setting multiple environment variables quickly after each other doesn't apply all

### ISSUE THREAD

**Issue by joshuajansen** [intercity/intercity-next#92]
I tried adding a couple environment variables through the web interface of our hosted instance earlier today and noticed that only the first 2 actually got set. They were persisted in IC, so they were visible in web-interface, but not available in the container of the app. This might be related with me adding them too quickly after each other?

**Comment by jvanbaarsen** [comment]
@joshuajansen I updated Dokku to 0.5.5 and can't reproduce it anymore. Once I pushed that I'll consider this to be fixed.
