### ISSUE TITLE
Intercity / Docker on same server gives installation problems

### ISSUE THREAD

**Issue by mterwoord** [intercity/intercity-next#96]
I tried to install intercity-docker on a clean Ubuntu 14.04 LTS machine. All works, until I add the machine as node in Intercity. It starts installing docker then (which is already installed at that point) and keeps working on that. Any way to get going? (Do I need another Linux distro?)

**Comment by jvanbaarsen** [comment]
Hi @mterwoord, Ubuntu 14.04 should be good. @michiels I remember you installed Intercity-Docker on a server which also serves as a Dokku server right? Did you run into this issue?

**Comment by michiels** [comment]
Hey @mterwood. Do you mean that you add the host system as a node in IC next? I did run into an issue that ithis didn't work the first time for me as well. I redid adding the server node and it worked.

Can you see if there are still any processes running on your node and maybe re-add the server?

**Comment by mterwoord** [comment]
I re-added the server, but now it gets stuck at adding the SSH public key.

**Comment by jvanbaarsen** [comment]
@mterwoord What do you mean with Getting stuck? It keeps checking if you added the correct SSH key?

**Comment by mterwoord** [comment]
Correct.

**Comment by jvanbaarsen** [comment]
@mterwoord Ok, did you add the SSH key showed there to the correct server on the root user?

**Comment by mterwoord** [comment]
I think so. I added it to the authorized_keys file in /root/.ssh and set the file to chmod 600. I did that before as well.

**Comment by jvanbaarsen** [comment]
Ok, are there any errors on the javascript console in your browser?

**Comment by mterwoord** [comment]
No errors there. It keeps polling ```/servers/2/test_ssh```, which responds 
with ```new ServerPoller("/servers/2/test_ssh").poll();```

**Comment by jvanbaarsen** [comment]
Ok, is the IP/hostname you entered for the server reachable over the internet?

**Comment by mterwoord** [comment]
Internet? no. Local LAN.

**Comment by jvanbaarsen** [comment]
@mterwoord Hm ok, that might be a problem, what the SSH key check is doing, it tries to SSH into your server, and performs a `sudo ls` command (To check if we have sudo rights). If the Intercity Server can't connect to the given IP address, we can't perform that command. 

You're using the Intercity server also as your app server right? What is the IP you entered? `127.0.0.1`?

**Comment by mterwoord** [comment]
It's a single VM (MS HyperV), running both intercity as well as docker. Initially i entered the dns name (which worked before). Right now, I tried using the LAN ip (192.168.50.64)
Should I use 127.0.0.1?

**Comment by jvanbaarsen** [comment]
At this point I'm curious to see if 127.0.0.1 will work. Can it be that SSH is blocked on your local network?

**Comment by mterwoord** [comment]
Shouldn't be locked. I'm managing the machine using ssh.

Too bad I can't change the existing settings. Now I have to reupload the authorized keys.
No luck wiht 127.0.0.1 either.

Maybe I should reinstall the VM and retry?

**Comment by jvanbaarsen** [comment]
I'll make a local install and give it a try! Will report back in 15 minutes or so :)

**Comment by jvanbaarsen** [comment]
@mterwoord I just checked with a fresh installation, I have the same problem, the SSH check keeps running. I'll consider this a bug, and will look into it!

**Comment by mterwoord** [comment]
Awesome!

(The fact that it's not just me...) :)

**Comment by jvanbaarsen** [comment]
@mterwoord I'm testing inside a vagrant environment. When I test it with the vagrant box IP address, it works.

Can you SSH into the server manually from your main machine? (On that given IP address)

**Comment by mterwoord** [comment]
Yes, I do that all the time.

In fact, I used ssh to upload the ssh keys.

**Comment by jvanbaarsen** [comment]
Hm ok weird :cry: So just to tick all boxes:

* You have a server running on IP: 192.168.50.64
* You can access that IP as follow: `ssh root@192.168.50.64` from your main machine?
* You installed Intercity using intercity-docker
* You can access Intercity on `http://192.168.50.64`

**Comment by mterwoord** [comment]
1: Correct
2: No: I connect using matthijs@192.18.50.64 and use sudo for doing root actions
3: Yes
4: Yes

**Comment by jvanbaarsen** [comment]
@mterwoord Ok, can you try connecting via `ssh root@192.168.50.64`?

**Comment by mterwoord** [comment]
We're on the right path here I think: http://askubuntu.com/questions/469143/how-to-enable-ssh-root-access-on-ubuntu-14-04

**Comment by mterwoord** [comment]
Hmm, after enabling that and setting a root password, I verified I could login using root. That worked, but still no luck with intercity....

**Comment by jvanbaarsen** [comment]
@mterwoord Ok, when you login via `ssh root@IP`, can you perform the `sudo ls` command without it asking for a password?

**Comment by mterwoord** [comment]
That works fine, but why would you use sudo ls instead of just ls?

**Comment by jvanbaarsen** [comment]
That serves as a check that we in fact have sudo access on the server (At this point we still need sudo access, working on removing that all together)

**Comment by jvanbaarsen** [comment]
@mterwoord Can you try and re-add a new server to Intercity with the 192.x.x.x address?

**Comment by mterwoord** [comment]
*sigh* Ownership of authorized keys was wrong. Very stupid of me..... 

It's installing docker again now...

**Comment by mterwoord** [comment]
I'll let it run for a while and report back later. Intercity is not reachable now.

**Comment by jvanbaarsen** [comment]
:+1:

**Comment by mterwoord** [comment]
Still not reachable..

**Comment by michiels** [comment]
@mterwoord just to confirm: you did a clean "manual" installation of Ubuntu LTS where the root user is disabled by default right?

**Comment by mterwoord** [comment]
Correct. I picked a normal server installation, with no automatic updates. Had the installer install SSH.
Next, all work was via SSH (so that's working fine).
Installed mc, did apt-get update && apt-get upgrade
then followed the intercity-docker instructions (well, slightly modified version, as it contains bugs..)

**Comment by michiels** [comment]
Alright. I'm not 100% sure if you've maybe already tried it. But what happens if you do `ssh root@localhost` and/or `ssh root@127.0.0.1` while you are already logged in as root on your server?

**Comment by mterwoord** [comment]
Just tried that: After allowing the server certificate, I was asked for the password, and then it works.

**Comment by michiels** [comment]
Ok. We might have something here because Intercity was probably also getting these questions which might have made it stuck. I think we can best debug if you can extract the private SSH key from IC and try it yourself on your command line. That way we simulate IC logging into localhost with the SSH key the best we can.

@jvanbaarsen You have any ideas on how to quickly extract the SSH private key from IC?

**Comment by mterwoord** [comment]
@michiels Right now, I think the setup is broken: intercity web interface is not getting up anymore. I'd say I repave the ubuntu VM, enable the root ssh stuff, and have the root user connect to root@::1 before installing intercity. After that, I'll get back here...

**Comment by michiels** [comment]
@mterwoord I think so too. Thanks for going through this process! I'll also re-verify what I did when I was installing a custom Ubuntu LTS server on TransIP two weeks ago.

**Comment by mterwoord** [comment]
If I wait long enough, intercity stops responding to http requests...

**Comment by michiels** [comment]
@mterwoord Hmm ok. What kind of server is this? Can you give us some specs in terms of CPU and available memory?

**Comment by mterwoord** [comment]
It's HyperV VM with 2 virtual CPU's and 8GB of memory assigned.
I tried rebooting, and then docker is removed. Trying to install it says that a previous install action crashed.

**Comment by mterwoord** [comment]
@michiels I could give you access to the machine if you want?

**Comment by michiels** [comment]
@mterwood that would be good too! Can you email me your Skype/other type of chat. My email is michiel@firmhouse.com

**Comment by jvanbaarsen** [comment]
Closing this issue for now. If you still experience problems, please comment in this issue, and I'll re-open.
